name: dd_js_util
description: flutter tools and widgets and extends
version: 6.2.6
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.9.0
  html: ^0.15.4
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  saver_gallery: ^3.0.5
  flutter_cache_manager: ^3.3.2
  image: ^4.2.0
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.9.7+8
  image_picker: ^1.1.2
  dio: ^5.5.0+1
  extended_image: ^8.2.1
  flutter_swiper_null_safety_flutter3: ^4.0.3
  url_launcher: ^6.3.0
  ffloat_nullsafety: ^3.3.6
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  logger: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.3
  fast_immutable_collections: ^10.2.4
  loading_more_list_fast: ^7.1.4
  loading_more_list_library_fast: ^4.1.3
  keyboard_actions: ^4.2.0
  json_annotation: ^4.9.0
  mime: ^1.0.5
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  async: ^2.11.0
  waterfall_flow: ^3.0.3
  extended_image_library: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.6
  hive_generator_plus: ^3.0.4


dependency_overrides:
  web: ^0.5.1
  meta: ^1.15.0