name: dd_js_util
description: flutter tools and widgets and extends
version: 6.5.6
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.9.0
  html: ^0.15.5
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  saver_gallery: ^4.0.1
  flutter_cache_manager: ^3.4.1
  image: ^4.5.2
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.9.8+5
  image_picker: ^1.1.2
  dio: ^5.7.0
  extended_image: ^9.1.0
  flutter_swiper_null_safety_flutter3: ^4.0.3
  url_launcher: ^6.3.1
  ffloat_nullsafety: ^3.3.6
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  logger: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_scheme: ^8.1.0
  freezed_annotation: ^2.4.4
  fast_immutable_collections: ^11.0.3
  loading_more_list_fast: ^7.1.8
  loading_more_list_library_fast: ^4.1.6
  keyboard_actions: ^4.2.0
  json_annotation: ^4.9.0
  mime: ^2.0.0
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  async: ^2.12.0
  waterfall_flow: ^3.1.0
  extended_image_library: ^4.0.5
  image_editor: ^1.6.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  hive_generator_plus: ^3.0.5

dependency_overrides:
  collection: ^1.19.1