name: dd_js_util
description: flutter tools and widgets and extends
version: 4.1.0
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.3
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  saver_gallery: ^2.0.1
  flutter_cache_manager: ^3.3.0
  image: ^4.0.17
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.9.0+6
  image_picker: ^0.8.7+5
  flutter_image_compress: ^2.0.3
  dio: ^5.1.2
  extended_image: ^8.0.2
  flutter_swiper_null_safety_flutter3: ^3.0.1
  url_launcher: ^6.1.11
  ffloat_nullsafety: ^3.3.6
  riverpod: ^2.3.6
  flutter_easyrefresh: ^2.2.2
  hooks_riverpod: ^2.3.6
  flutter_lints: ^2.0.1
  logger: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fbroadcast_nullsafety: ^3.0.0
  flex_color_scheme: ^7.1.2
  extended_image_library: ^3.5.1
  freezed_annotation: ^2.2.0
  fast_immutable_collections: ^9.1.5
  loading_more_list_fast: ^6.0.1
  loading_more_list_library_fast: ^3.0.1
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  analyzer: ^5.13.0
  json_serializable: ^6.7.0
  hive_generator: ^2.0.0
  freezed: ^2.3.4
  custom_lint: ^0.4.0

