name: dd_js_util
description: flutter tools and widgets and extends
version: 5.1.7
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  html: ^0.15.4
  permission_handler: ^11.1.0
  cached_network_image: ^3.3.1
  saver_gallery: ^3.0.1
  flutter_cache_manager: ^3.3.1
  image: ^4.1.3
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.9.6
  image_picker: ^1.0.7
  dio: ^5.4.0
  extended_image: ^8.2.0
  flutter_swiper_null_safety_flutter3: ^4.0.2
  url_launcher: ^6.2.3
  ffloat_nullsafety: ^3.3.6
  riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  logger: ^2.0.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1
  fast_immutable_collections: ^9.2.0
  loading_more_list_fast: ^7.0.5
  loading_more_list_library_fast: ^4.0.4
  keyboard_actions: ^4.2.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  isar_flutter_libs: ^3.1.0+1
  async: ^2.11.0
  waterfall_flow: ^3.0.3


dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator_plus: ^3.0.4


dependency_overrides:
  meta: ^1.11.0