name: dd_js_util
description: 梁典典的常用工具类封装
version: 2.1.7+3
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.1
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  waterfall_flow: ^3.0.2
  image: ^3.2.2
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.7.1
  image_picker: ^0.8.6
  flutter_image_compress: ^1.1.3
  dio: ^4.0.6
  extended_image: ^6.3.2
  flutter_swiper_null_safety_flutter3: ^3.0.0
  url_launcher: ^6.1.7
  ffloat_nullsafety: ^3.3.1
  riverpod: ^2.1.1
  flutter_easyrefresh: ^2.2.2
  hooks_riverpod: ^2.1.1
  flutter_lints: ^2.0.1
  logger: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.6.0
  fbroadcast_nullsafety: ^3.0.0
  flex_color_scheme: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  analyzer: ^5.2.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_js_util
        pluginClass: DdJsUtilPlugin
      ios:
        pluginClass: DdJsUtilPlugin
      windows:
        pluginClass: DdJsUtilPlugin
      web:
        pluginClass: DdJsUtilWeb
        fileName: dd_js_util_web.dart

