name: dd_js_util
description: Flutterweb端工具类
version: 0.5.4
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: any
  image_gallery_saver: any
  cached_network_image: any
  flutter_cache_manager: any
  waterfall_flow: any
  image: any
  common_utils: any
  flutter_smart_dialog: any
  image_picker: any
  flutter_image_compress: any
  dio: any
  extended_image: any
  flutter_swiper_null_safety_flutter3: any
  flutter_web_plugins:
    sdk: flutter
  url_launcher: any
  ffloat_nullsafety: any
  riverpod: any
  flutter_easyrefresh: any
  hooks_riverpod: any
  flutter_lints: any
  logger: any
  hive: ^2.2.3
  flutter_screenutil: ^5.5.4
  fbroadcast_nullsafety: any
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_js_util
        pluginClass: DdJsUtilPlugin
      ios:
        pluginClass: DdJsUtilPlugin
      windows:
        pluginClass: DdJsUtilPlugin
      web:
        pluginClass: DdJsUtilWeb
        fileName: dd_js_util_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
