name: dd_js_util
description: flutter tools and widgets and extends
version: 6.4.0
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.9.0
  html: ^0.15.4
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  saver_gallery: ^3.0.6
  flutter_cache_manager: ^3.4.1
  image: ^4.2.0
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.9.8+3
  image_picker: ^1.1.2
  dio: ^5.7.0
  extended_image: ^8.3.1
  flutter_swiper_null_safety_flutter3: ^4.0.3
  url_launcher: ^6.3.1
  ffloat_nullsafety: ^3.3.6
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.2
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.4
  fast_immutable_collections: ^10.2.4
  loading_more_list_fast: ^7.1.7
  loading_more_list_library_fast: ^4.1.5
  keyboard_actions: ^4.2.0
  json_annotation: ^4.9.0
  mime: ^1.0.6
  package_info_plus: ^8.0.3
  device_info_plus: ^11.0.0
  async: ^2.11.0
  waterfall_flow: ^3.0.3
  extended_image_library: ^4.0.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  hive_generator_plus: ^3.0.5

dependency_overrides:
  collection: 1.19.0