name: dd_js_util
description: 梁典典的常用工具类封装
version: 3.0.2
homepage: https://github.com/mdddj/dd_js_util

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.1
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  waterfall_flow: ^3.0.2
  image: ^4.0.13
  common_utils: ^2.1.0
  flutter_smart_dialog: ^4.8.2+3
  image_picker: ^0.8.6+1
  flutter_image_compress: ^1.1.3
  diox: ^5.0.0
  extended_image: ^7.0.0
  flutter_swiper_null_safety_flutter3: ^3.0.0
  url_launcher: ^6.1.9
  ffloat_nullsafety: ^3.3.1
  riverpod: ^2.1.3
  flutter_easyrefresh: ^2.2.2
  hooks_riverpod: ^2.1.3
  flutter_lints: ^2.0.1
  logger: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.6.1
  fbroadcast_nullsafety: ^3.0.0
  flex_color_scheme: ^6.1.2
  extended_image_library: ^3.4.1
  freezed_annotation: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  analyzer: ^5.4.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  freezed: ^2.3.2


flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_js_util
        pluginClass: DdJsUtilPlugin
      ios:
        pluginClass: DdJsUtilPlugin
      windows:
        pluginClass: DdJsUtilPlugin
      web:
        pluginClass: DdJsUtilWeb
        fileName: dd_js_util_web.dart

